### ISSUE TITLE
Host servo-starters under servo.org

### ISSUE THREAD

**Issue by jdm** [servo/servo.org_2014-2020#2]
If we include a submodule for it here, will that just magically work?

**Comment by jdm** [comment]
cc @metajack @larsbergstrom

**Comment by Manishearth** [comment]
Alternatively, create the repository `servo/servo-starters`, use a gh-pages branch, and it should automatically show up at `servo.org/servo-starters`. I think.

**Comment by jdm** [comment]
orly! That sounds eminently doable: https://github.com/servo/servo-starters

**Comment by SimonSapin** [comment]
I don’t think it’ll automatically use a "sub-directory" with custom domains.

Assuming you want to host on GitHub Pages, you’ll need to:
- Use the `gh-pages` branch (you already do)
- Add a `CNAME` file at the root of the repo in that branch containing e.g. `starters.servo.org`
- Configure the servo.org DNS so that the relevant subdomain is a CNAME record to `servo.github.io`. Requests for that used to go [on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1061167), but that "product" has been renamed "mozilla.org Graveyard", so I don’t know where they should go now. @edunham, do you know?

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

I like the repo name to be the same as the DNS name (e.g. https://github.com/servo/blog.servo.org) but that’s not required.

**Comment by edunham** [comment]
It's currently online at http://servo.github.io/servo-starters/ . I haven't actually made DNS changes for Servo yet; when we figure it out I'd like to write it down in https://github.com/servo/servo/wiki/Infrastructure . @larsbergstrom or @metajack probably knows the process.

**Comment by larsbergstrom** [comment]
servo.org is maintained by Mozilla IT; you just open a bugzilla bug and the magical Mozilla #it staff handle it for us :-)

e.g., https://bugzilla.mozilla.org/show_bug.cgi?id=1049897

**Comment by jdm** [comment]
I've opened https://github.com/servo/servo.org/pull/3 to get `servo.org/starters/` to redirect to the published version.

**Comment by edunham** [comment]
`starters.servo.org` now redirects to HTTPS and keeps the `starters.servo.org` URL rather than redirecting to the github.io site
